name: Deploy Notion Content

on:
  workflow_dispatch:
    # This means you can manually trigger from the Actions tab

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Fetch Notion content
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: npm run fetch-notion

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # This action will automatically push the contents of ./public
          # to the gh-pages branch
