name: Deploy Notion Content

on:
  workflow_dispatch:
    # This means you can manually trigger from the Actions tab

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out your repo so we can access the code and scripts
      - name: Check out repo
        uses: actions/checkout@v3

      # 2) Set up the Node.js environment
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3) Install your dependencies (from package.json)
      - name: Install dependencies
        run: npm install

      # 4) Fetch Notion content (this uses the script in "scripts/fetch-notion.js")
      - name: Fetch Notion content
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}   # Must be in your repo's Secrets
        run: npm run fetch-notion

      # 5) Deploy to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # We deploy to gh-pages branch instead of main
          publish_branch: gh-pages
